# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-14 07:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalityDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=50)),
                ('question', models.CharField(max_length=3)),
                ('answer', models.IntegerField(max_length=2)),
            ],
        ),
    ]
