# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-14 11:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyPersonality', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalitydetails',
            name='id',
        ),
        migrations.AlterField(
            model_name='personalitydetails',
            name='userName',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
