# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-14 11:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyPersonality', '0002_auto_20180214_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalitydetails',
            name='id',
            field=models.AutoField(auto_created=True, default='TestUser', primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='personalitydetails',
            name='userName',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='personalitydetails',
            unique_together=set([('userName', 'question')]),
        ),
    ]
