# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-14 11:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyPersonality', '0003_auto_20180214_1704'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='personalitydetails',
            unique_together=set([]),
        ),
    ]
